In [4]:
import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv(r"C:\Users\Hp\Desktop\Python\E-Commerce Dataset\ecommerce sales customer analytics.csv")
df.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8

In [19]:
df.shape[0] #number of rows

138116

In [20]:
df.shape[1] #number of columns

46

In [22]:
df.isna().sum()

order_id                         0
order_date                       0
order_time                       0
order_status                     0
sales_channel                    0
customer_id                      0
customer_name                    0
customer_age                     0
gender                           0
customer_segment                 0
customer_type                    0
customer_city                    0
customer_state                   0
customer_country                 0
region                           0
customer_postal_code             0
payment_method                   0
payment_status                   0
currency                         0
shipping_method                  0
warehouse                        0
delivery_days                24557
estimated_delivery_days      24557
delivery_status                  0
return_status               128654
return_reason               128654
customer_rating              24557
review_sentiment             24557
customer_review              24557
marketing_channel                0
campaign_name                83233
coupon_code                 110502
loyalty_points_earned            0
loyalty_points_redeemed          0
quantity                         0
gross_sales                      0
discount_amount                  0
tax_amount                       0
shipping_cost                    0
net_sales                        0
product_cost                     0
profit                           0
profit_margin_percentage         0
customer_lifetime_value          0
is_repeat_customer               0
customer_order_count             0
dtype: int64

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  str
 1   order_date                138116 non-null  str
 2   order_time                138116 non-null  str
 3   order_status              138116 non-null  str
 4   sales_channel             138116 non-null  str
 5   customer_id               138116 non-null  str
 6   customer_name             138116 non-null  str
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  str
 9   customer_segment          138116 non-null  str
 10  customer_type             138116 non-null  str
 11  customer_city             138116 non-null  str
 12  customer_state            138116 non-null  str
 13  customer_country          138116 non-null  str
 14  region                    138116 non-null  str
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  str
 17  payment_status            138116 non-null  str
 18  currency                  138116 non-null  str
 19  shipping_method           138116 non-null  str
 20  warehouse                 138116 non-null  str
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  str
 24  return_status             9462 non-null    str
 25  return_reason             9462 non-null    str
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  str
 28  customer_review           113559 non-null  str
 29  marketing_channel         138116 non-null  str
 30  campaign_name             54883 non-null   str
 31  coupon_code               27614 non-null   str
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), str(27)
memory usage: 47.6 MB

In [28]:
df['order_id'].dtypes

In [30]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
138111    False
138112    False
138113    False
138114    False
138115    False
Length: 138116, dtype: bool

In [36]:
int(df['net_sales'].sum()) #total revenue

177134263

In [34]:
int(df['profit'].sum()) #total profit

76146395

In [38]:
int(df['net_sales'].mean())

1282

In [40]:
int(df['quantity'].sum()) #quantity sold

775555

In [44]:
df.groupby('customer_id')['net_sales'].sum().sort_values(ascending = False).head(10) # Top 10 customers based on total revenue.

customer_id
CUST-012869    30268.44
CUST-002969    30061.58
CUST-017251    29375.34
CUST-000802    28503.23
CUST-012608    28172.12
CUST-017828    28092.99
CUST-006857    26835.08
CUST-017523    26776.65
CUST-008822    25803.66
CUST-001747    25737.14
Name: net_sales, dtype: float64

In [50]:
df.groupby('region')[['net_sales','profit','customer_order_count']].sum() #revenue, profit, and order count for each country/region.

           net_sales       profit  customer_order_count
region
Central  37171107.17  15572868.84                208717
East     27054887.88  11179366.94                152408
North    22565177.24  10402961.34                115128
South    55587994.98  23343946.17                305652
West     34755096.47  15647252.47                183603

In [53]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['year'] = df['order_date'].dt.year

In [55]:
df['month'] = df['order_date'].dt.month

In [57]:
df.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count,year,month
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,12.03,945.40,588.33,345.04,36.50,12459.68,True,11,2023,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11,2025,12
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,13.05,468.35,257.73,197.57,42.18,6159.44,True,6,2021,7
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,20.85,546.52,277.84,247.83,45.35,5638.30,True,7,2023,1
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8,2022,5

In [58]:
df.groupby(['year','month'])['net_sales'].sum() # Yearly and monthly revenue and identify the best-performing period.

year  month
2021  1        2374415.22
      2        1905413.15
      3        2753256.18
      4        2469384.78
      5        2546555.37
      6        2710208.64
      7        2894416.72
      8        3220659.48
      9        2720931.59
      10       2991778.76
      11       4234660.71
      12       4900970.07
2022  1        2442770.60
      2        2029412.22
      3        2682800.73
      4        2516740.73
      5        2529145.45
      6        2697622.96
      7        2765292.19
      8        2947796.56
      9        2750776.22
      10       2925151.89
      11       4405731.78
      12       4634641.29
2023  1        2467972.04
      2        2035382.66
      3        2700460.99
      4        2495710.76
      5        2555496.97
      6        2801712.97
      7        2715818.33
      8        3070356.42
      9        2747363.20
      10       3001350.13
      11       4261793.39
      12       4674725.88
2024  1        2510721.37
      2        2119755.19
      3        2752681.57
      4        2635743.36
      5        2579097.07
      6        2639763.54
      7        2833868.86
      8        2860775.42
      9        2754826.02
      10       2894022.77
      11       4352110.30
      12       4533086.81
2025  1        2442719.60
      2        2018064.34
      3        2790317.39
      4        2536513.26
      5        2416435.27
      6        2621595.83
      7        2844927.97
      8        2958759.35
      9        2840833.95
      10       2793772.97
      11       4270161.00
      12       4555033.50
Name: net_sales, dtype: float64

In [62]:
df['avg_oreder_valueint'] = (df['net_sales'].mean())

1282

In [66]:
df.groupby('customer_segment')[['net_sales','profit']].sum()

                    net_sales       profit
customer_segment
Business          17760296.90   7782525.28
Consumer          97201007.90  42819790.02
Premium           44269794.13  18177727.78
VIP               17903164.81   7366352.68

In [67]:
df['discount_percentage'] = (df['discount_amount'] / df['gross_sales']) * 100

In [68]:
df[['gross_sales', 'discount_amount', 'discount_percentage', 'profit']].head() # Relationship between discount and profit to determine whether higher discounts are beneficial.

   gross_sales  discount_amount  discount_percentage   profit
0      1350.19           477.89            35.394278   345.04
1      3144.64          1456.06            46.302915   -22.47
2       522.81            97.30            18.610968   197.57
3       544.62            53.34             9.793985   247.83
4      2474.52           133.63             5.400239  1530.36

In [69]:
df.groupby('customer_id')[['net_sales','profit','customer_order_count','customer_lifetime_value']].sum().sort_values('net_sales', ascending=False).head(10) # Top 10 most valuable customers using revenue, profit, order frequency, and CLV.

,net_sales,profit,customer_order_count,customer_lifetime_value
customer_id,,,,
CUST-012869,30268.44,11818.95,225,454026.60
CUST-002969,30061.58,11703.80,256,480985.28
CUST-017251,29375.34,10563.05,225,440630.10
CUST-000802,28503.23,12782.04,156,349895.04
CUST-012608,28172.12,13993.62,169,366237.56
CUST-017828,28092.99,12397.89,196,393301.86
CUST-006857,26835.08,9357.22,110,274308.80
CUST-017523,26776.65,12663.43,81,240989.85
CUST-008822,25803.66,11059.20,100,258036.60
CUST-001747,25737.14,11624.00,225,386057.10

In [70]:
loss_orders = df[df['profit'] < 0]

In [71]:
loss_orders.shape[0]

1296

In [72]:
loss_orders[['order_id','net_sales','discount_amount','product_cost','shipping_cost','profit']].head(10)

,order_id,net_sales,discount_amount,product_cost,shipping_cost,profit
1,ORD-773460,2018.41,1456.06,2031.88,9.00,-22.47
149,ORD-567393,2826.85,2943.84,2886.87,29.48,-89.50
156,ORD-613985,2011.70,1683.01,2202.05,11.09,-201.44
158,ORD-324161,161.97,111.35,170.91,3.22,-12.16
163,ORD-828591,2298.28,2150.22,2533.00,5.77,-240.49
266,ORD-459603,296.68,399.13,331.44,11.96,-46.72
552,ORD-685844,1060.25,675.84,1044.25,21.54,-5.54
773,ORD-590144,1199.62,768.89,1198.53,20.00,-18.91
1078,ORD-887807,1931.74,1502.36,1955.84,36.28,-60.38
1086,ORD-990629,1101.93,1267.92,1275.35,3.38,-176.80